version: '3.7'

services:

    php:
        container_name: ${NAME}_php
        image: radoslawniestroj/php-fpm-xdebug:8.1
        links:
            - elasticsearch
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ~/.composer:/var/www/.composer
        environment:
            XDEBUG_CONFIG: "remote_host=${XDEBUG_HOST_IP} idekey=${XDEBUG_IDE_KEY}"
            PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVERNAME}"
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    nginx:
        container_name: ${NAME}_nginx
        image: radoslawniestroj/nginx:18.04
        ports:
            - ${NGINX_PORT}:8000
            - ${NGINX_PROXY_UNSECURE_PORT}:80
            - ${NGINX_PROXY_SECURE_PORT}:443
        links:
            - php
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/nginx:/etc/nginx/sites-available
            - .:/var/www/html

    varnish:
        container_name: ${DOMAIN_NAME}
        image: radoslawniestroj/varnish:latest
        ports:
            - ${VARNISH_PORT}:6081
        links:
            - nginx
        environment:
            BACKENDS: ${DOMAIN_NAME}
            BACKENDS_PORT: ${NGINX_PORT}
            BACKENDS_PROBE_INTERVAL: 6000s
        volumes:
            - ./docker/varnish/default.vcl:/etc/varnish/default.vcl

    mysql:
        container_name: ${NAME}_db
        image: mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASS}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - ./docker/data/mysql:/var/lib/mysql

    postgresql:
        container_name: ${NAME}_postgresql
        image: sameersbn/postgresql:9.6-2
        ports:
            - ${POSTGRESQL_PORT}:5432
        environment:
            DB_USER: ${POSTGRESQL_USER}
            DB_PASS: ${POSTGRESQL_PASS}
            DB_NAME: ${POSTGRESQL_DB}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - postgreqsl_data:/var/lib/postgresql/

    adminer:
        container_name: ${NAME}_adminer
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}

    elasticsearch:
        container_name: ${NAME}_elasticsearch
        image: radoslawniestroj/elasticsearch:7.17.6
        ports:
            - ${ELASTICSEARCH_PORT}:9200
        environment:
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
            discovery.type: single-node
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
            - elasticsearch_config:/usr/share/elasticsearch/config

    redis:
        container_name: ${NAME}_redis
        image: bitnami/redis:latest
        ports:
            - ${REDIS_PORT}:6379
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            COLUMNS: ${TERMINAL_COLS}
            LINES: ${TERMINAL_LINES}
        volumes:
            - redis_data:/bitnami

    mailhog:
        container_name: ${NAME}_mailhog
        image: mailhog/mailhog:v1.0.0
        ports:
            - 1025:1025
            - 8025:8025

volumes:
    postgreqsl_data:
    redis_data:
    elasticsearch_data:
    elasticsearch_config:
    mysql_data:
    project-sync:
        external: true
